Jekyll site CI
Update scrape_talks.yml #1
All jobs
Run details
Triggered via push 1 minute ago
@soutofersoutofer
pushed
 8e2a5a7
master
Status
Success
Total duration
32s
Artifacts
1


Annotations
1 warning
build
The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
Artifacts
Produced during runtime
Name	Size	Digest	
github-pages
13.7 MB	
sha256:a573b98d95abe1a1a1ce9e2defee3cfe07b94e5c4f5cf4b4b6d3011a5e1d2631
